graph TD
    Title["The IDE won't work"]
    Title --> |Start| WatchedVideo
    WatchedVideo["Have you watched the video at https://ide.crunchlabs.com/downloads?"]
    WatchedVideo --> |No| GoWatchVideo
    WatchedVideo --> |Yes| OS
    GoWatchVideo["Please watch the video at https://ide.crunchlabs.com/downloads before proceeding."]
    GoWatchVideo --> |Proceed| WatchedVideo
    OS["What Operating System do you use? (What type of computer)"]
    OS --> |Windows| Windows
    OS --> |Mac| Mac
    OS --> |Chromebook| Chromebook
    OS --> |Linux| Linux
    OS --> |Other| Other
    Windows["If you click the up arrow near the wifi icon, do you see a white circle with the Hack Pack logo?"]
    Windows --> |No| WindowsInstallAgent
    Windows --> |Yes| BrowserCheck
    Mac["Do you see a white circle with the hack pack logo on the right side of the bar at the top of your screen?"]
    Mac --> |No| MacInstallAgent
    Mac --> |Yes| BrowserCheck
    Chromebook["Chromebooks are not officially supported. However, you can still use the Arduino Cloud if you are willing to figure things out yourself."]
    Linux["Request help in #ide-help-chat of the Hack Pack discord."]
    Other["Request help in #ide-help-chat of the Hack Pack discord."]
    WindowsInstallAgent["If you have already installed the create agent as in the video, you likely need to run it as administrator. Open windows search, type #quot;Crunchlabs#quot;, right-click item ***without*** the word #quot;setup#quot;, and click #quot;Run As Administrator#quot;"]
    BrowserCheck["Are you using Chrome as your browser, and have you disabled any content-blocking extensions?"]
    BrowserCheck --> |Yes| ProvidedCableCheck
    MacInstallAgent["Refer to the downloads video for how to install the create agent on mac. If you need additional help, ask in #ide-help-chat"]
    ProvidedCableCheck["Are you using the provided USB-C to USB-A cable?"]
    ProvidedCableCheck --> |Yes| ArduinoPortCheck
    ArduinoPortCheck["Are you connecting the cable from your computer to the silver USB-C port on the microcontroller, ***not*** the black breadboard box?"]
    ArduinoPortCheck --> |Yes| Restart
    Restart["Disable bluetooth on your computer and restart it. Windows users, start the agent as administrator again. Does it work now?"]
    Restart --> |No| RequestHelpSupported
    RequestHelpSupported["Request help in #ide-help-chat of the Hack Pack discord."]
    
    %% Node-specific styling
    style Title white-space:nowrap
    style Title stroke-width:3px;

    %% templateColor #57899E